@startuml
'https://plantuml.com/class-diagram

Class UserInput
{
    getOutputFileName
}
Class ReadFile
{
    readFileToString()

}

Class ReplaceWords
{
    replaceUtilizeWithUse (String fileString)
            return replacedFileString
}

Class WriteFile
{
    generateOutputFile(String replacedFileString, String outputFileName)
    createFileDir(String outputFileName)
}


ReadFile --|> ReplaceWords
ReplaceWords --|> WriteFile
UserInput --|> WriteFile


@enduml